# Generated by Django 2.2.16 on 2020-12-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_auto_20201226_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuilD_Profile',
        ),
    ]
