# Generated by Django 2.2.16 on 2020-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build_profile',
            name='image',
            field=models.ImageField(default='img', upload_to='img/%y'),
        ),
    ]
